<robot name="myCar"  xmlns:xacro="http://wiki.ros.org/xacro" >

   <xacro:property name="footprint_radius" value="0.001" />

   <link name="base_footprint">
             <visual>
                  <geometry>
                        <sphere radius="${footprint_radius}" />
                  </geometry>
            </visual>
       </link>

       <!-- add chasiss -->
       <xacro:property name="base_radius" value="0.1" />
       <xacro:property name="base_length" value="0.08" />
      <xacro:property name="base_mass" value="2" />
       <xacro:property name="ground_clerence" value="0.015" />
      <xacro:property name="base_joint_z" value="${base_length/2 +ground_clerence}" />

      <link name="base_link" >
            <visual>
                  <geometry>
                        <cylinder radius="${base_radius}" length="${base_length}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy ="0 0 0" />
                  <material name="yellow" >
                        <color rgba="0.5  0.5 0.1 0.5"  />
                  </material>
                  
            </visual>
            <collision>
                   <geometry>
                        <cylinder radius="${base_radius}" length="${base_length}" />
                  </geometry>
                   <origin xyz="0 0 0" rpy ="0 0 0" />
            </collision>
            <xacro:cylinder_inertial_matrix  m="${base_mass}" r="${base_radius}" h="${base_length}" />
      </link>
      <gazebo reference="base_link" >
            <material>Gazebo/Yellow</material>
      </gazebo>

      <joint name="base_link2basefootprint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz=" 0 0 ${base_joint_z} " rpy="0 0 0" />
      </joint>

      <xacro:property name="wheel_radius" value="0.0325" />
      <xacro:property name="wheel_length" value="0.015" />
      <xacro:property name="wheel_mass" value="1" />
      <xacro:property name="PI" value="3.1415926" />
      <xacro:property name="wheel_joint_z" value="${-1*(base_length/2+ground_clerence -wheel_radius)}" />

      <!-- add wheel -->
      <xacro:macro  name="wheel_func" params="wheel_name flag">
      <link name="${wheel_name}_wheel">
            <visual>
                  <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="${0.5*PI} 0 0" />
                  <material name="black" >
                        <color  rgba="0 0 0 0.5" />
                  </material>
            </visual>
            <collision>
                   <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="${0.5*PI} 0 0" />
            </collision>
            <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
      </link>
      <gazebo reference="${wheel_name}_wheel">
            <material>Gazebo/Black</material>
      </gazebo>




      <joint name="${wheel_name}2base" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <origin xyz="0 ${flag*0.1} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
      </joint>
   </xacro:macro >
   <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />
    <!-- add ALL  boll -->
      <xacro:property name="boll_radius" value="0.0075" />
      <xacro:property name="boll_mass" value="0.1" />
      <xacro:macro name="boll_wheel" params="name flag" >
       <link name="${name}_boll">
            <visual>
                  <geometry>
                        <sphere radius="${boll_radius}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="0 0 0" />
                  <material name="boll_black" >
                        <color  rgba="0 1 0 0.5" />
                  </material>
            </visual>
            <collision>
                  <geometry>
                        <sphere radius="${boll_radius}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="${boll_mass}" r="${boll_radius}" />
      </link>

      <gazebo reference="${name}_boll">
            <material>Gazebo/Red</material>
      </gazebo>

        <joint name="${name}_boll2base" type="continuous">
            <parent link="base_link" />
            <child link="${name}_boll" />
            <origin xyz="${flag*(base_radius - boll_radius )}  0  ${-1*(base_length/2 +ground_clerence -boll_radius)}" rpy="0 0 0" />
            <axis xyz="1 1 1"/>
      </joint>
      </xacro:macro>
<xacro:boll_wheel name="front" flag="1" />
<xacro:boll_wheel name="rear" flag="-1" />
</robot>