<robot name="depth_camera"  xmlns:xacro="http://wiki.ros.org/xacro" >
      <xacro:property name="depth_camera_mass" value="0.05" />
      <xacro:property name="depth_camera_r" value="0.01" />
      <link name="depth_camera" >
            <visual>
                  <geometry>
                        <sphere radius="${depth_camera_r}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="0 0 0" />
                  <material name="blue" >
                        <color rgba=" 0 0 1 0.5" />
                  </material>
            </visual>
            <collision>
                  <geometry>
                        <sphere radius="${depth_camera_r}" />
                  </geometry>
                  <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="${depth_camera_mass}" r="${depth_camera_r}" />
      </link>
      <gazebo reference="depth_camera" >
      <material>Gazebo/Blue</material>
      </gazebo>

      <joint name="d_camera2camera" type="fixed">
            <parent link="camera" />
            <child link ="depth_camera" />
            <axis xyz="0 0 0"/>
            <origin xyz="0 0 ${0.5*(depth_camera_r+camera_z)}" rpy="0 0 0" />


      </joint>

</robot>